version: '3'
services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: app/Dockerfile
    volumes:
      - ./app:/app
    environment:
      VITE_BASE_URL: http://localhost:5173
      VITE_API_URL: http://localhost:8080
    restart: always
    ports:
      - '5173:5173'
    depends_on:
      - api

  api:
    container_name: api
    build:
      context: .
      dockerfile: server/Dockerfile
    volumes:
      - ./server:/server
    environment:
      MONGO_URI: 'mongodb://mongo:27017/test'
      MONGODB_HOST: mongo:27017
      MONGODB_USER: test
      MONGODB_PASSWORD: test
    restart: always
    ports:
      - '8080:8080'
    depends_on:
      - mongo

  mongo:
    container_name: mongo
    image: 'mongo:latest'
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: test
      MONGO_INITDB_ROOT_PASSWORD: test
